USE [MyDB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS MST_APPLICATION_TBL
CREATE TABLE [dbo].[MST_APPLICATION_TBL](
	[RunninNO] [int] IDENTITY(1,1) NOT NULL,
	[ApplicationID] [nvarchar](100) NOT NULL,
	[StageID] [int] NOT NULL,
	[SessionID] [int] NOT NULL,
	[CreatedBy] [nvarchar](100) NULL,
	[CreatedDate] [datetime] NULL,
	[UpdatedBy] [nvarchar](100) NULL,
	[UpdatedDate] [datetime] NULL,
	[ActiveStatus] [char](1) NULL,
 CONSTRAINT [PK_MST_APPLICATION_TBL] PRIMARY KEY CLUSTERED 
(
	[RunninNO] ASC,
	[ApplicationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MST_APPLICATION_TBL] ADD  CONSTRAINT [DF_MST_APPLICATION_TBL_CreatedDate]  DEFAULT (getdate()) FOR [CreatedDate]
GO

ALTER TABLE [dbo].[MST_APPLICATION_TBL] ADD  CONSTRAINT [DF_MST_APPLICATION_TBL_ActiveStatus]  DEFAULT ('N') FOR [ActiveStatus]
GO


