USE [MyDB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS SESSION_D_PAST_EMPL_DTL_TBL
CREATE TABLE [dbo].[SESSION_D_PAST_EMPL_DTL_TBL](
	[RunninNO] [int] IDENTITY(1,1) NOT NULL,
	[MST_REF_ID] [nvarchar](20) NOT NULL,
	[PAST_COMP_NAME] [nvarchar](max) NULL,
	[PAST_JOB_TITLE] [nvarchar](max) NULL,
	[PAST_EXP] [nvarchar](max) NULL,
 CONSTRAINT [PK_SESSION_D_PAST_EMPL_DTL_TBL] PRIMARY KEY CLUSTERED 
(
	[RunninNO] ASC,
	[MST_REF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


